name: null
favicon: null
layout_spectrum: 0.5980167691595852
typography_spectrum: 0.6834983096923679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8144515787716955
  lightness: 0.594011060660705
  saturation: 0.572917708195746
  rhythmicContrast: 0.1071774058509618
purpose: []
